// Generated by build_vehicles_data.py. Do not edit by hand.
// Providers: 1 | Listings: 0
window.vehicleProviders = [{"id":"scp","name":"Spanish Coast Properties","logo":"assets/header-logo.png","phone":"+34624867866","email":"info@spanishcoastproperties.com","website":"https://www.spanishcoastproperties.com"}];
window.vehicleListings = [];
